### ISSUE TITLE
B2C Provider not working

### ISSUE THREAD

**Issue by devtpsingh** [intelequia/dnn.azureadb2cprovider#24] opened 2021-06-24 06:16 UTC
While installing this B2C provider in DNN Evoq getting this error https://i.stack.imgur.com/6faW1.png
After this error when page refresh then B2C provider are showing into setting icons and after setup configuration it's redirect to login page and authenticate username and password and redirect at my portal but logout and Given name not displayed at my DNN portal.
Refirect URL
https://www.mywebsite.com/?state=s%3dAzureB2C%3bp%3d0%3bc%3den-US&code=.....

Please help me on this.

**Comment by davidjrh** [comment] 2021-06-24 09:42
This sounds like an issue in the manifest file. I’ll check the package build and let you know.

**Comment by davidjrh** [comment] 2021-06-24 09:43
And effectivey, is a duplicate of the #19. Closing this and continuing in the other thread.

**Closed by davidjrh** 2021-06-24 09:43 UTC
